### ISSUE TITLE
Movement Listener throwing null pointer

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/Borough#19]
`[14:24:32 WARN]: [Borough] Plugin Borough v0.0.1 generated an exception while executing task 459896
java.lang.NullPointerException: Cannot invoke "net.peacefulcraft.borough.storage.BoroughClaim.getClaimId()" because the return value of "net.peacefulcraft.borough.storage.BoroughChunk.getClaimMeta()" is null
        at net.peacefulcraft.borough.listeners.PlayerMovementListener.lambda$0(PlayerMovementListener.java:45) ~[Borough-0.0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-77]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-77]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by BrokenKage** [comment]
Chunk passing as 'isClaimed', but returning NULL on getClaimMeta
